kuka_kr6r900sixx:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  # Position Controllers ---------------------------------------
  joint_a1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a6
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Mors_prismatic1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Mors_prismatic1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Mors_prismatic2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Mors_prismatic2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Mors_prismatic3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: Mors_prismatic3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
